#!/bin/bash

. /usr/local/etc/rs-backup/server-config

# Take precautions :-)
if [ "${BACKUP_ROOT}" == "" ] || [ "$(realpath ${BACKUP_ROOT})" == "/" ]; then
	echo "Sorry, won't overwrite real '/etc/passwd'!"
	exit 1
fi

cat /etc/passwd | grep "::${BACKUP_ROOT}/[^/:]\+:/bin/[^:]\+$" > "${BACKUP_ROOT}/etc/passwd"
